[package]
name = "strong-xml-test-suite"
version = "0.1.0"
authors = ["PoiScript <poiscript@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
strong-xml = { path = "../strong-xml", features = ["log"] }
log = "0.4.8"
env_logger = "0.7.1"
