[package]
name = "xmlparser-derive-utils"
version = "0.1.0"
authors = ["PoiScript <poiscript@gmail.com>"]
edition = "2018"

[dependencies]
jetscii = "0.4.4"
lazy_static = "1.4.0"
memchr = "2.3.2"
xmlparser = "0.13.0"
