[package]
name = "strong_xml_test_suite"
version = "0.1.0"
authors = ["PoiScript <poiscript@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
strong-xml = { path = "../strong-xml" }
xmlparser = "0.13.0"
log = "0.4.8"
env_logger = "0.7.1"
